env = Environment(CC = 'gcc',
		  CPPPATH=['/home/karthik/Karthik/paho.mqtt.c/src'],
		  LIBPATH=['/home/karthik/Karthik/paho.mqtt.c/build/output'],
	          LIBS=['paho-mqtt3c'])
env.Program('pub_paho', 'paho_pub.c')
env.Program('sub_paho', 'paho_sub.c')



